/**
 * Nova Mission Engine — Planner
 * Uses Gemini to decompose a user goal into a multi-step plan.
 * The plan respects tool availability, dependencies, and parallelism.
 */

import { callGemini } from "@/lib/gemini";
import { toolRegistry } from "@/services/agent/ToolRegistry";
import type { MissionPlan, MissionStep } from "./MissionTypes";
import { DEFAULT_MAX_STEP_RETRIES } from "./MissionTypes";

// ─── Plan Generation ─────────────────────────────────────────────────────────

/**
 * Generate a multi-step plan for a user goal.
 * Returns a structured plan with ordered steps, dependencies, and parallelism info.
 */
export async function generatePlan(
  goal: string,
  geminiKey: string
): Promise<MissionPlan> {
  const tools = toolRegistry.listAvailable();
  const toolDescriptions = tools
    .map(
      (t) =>
        `- ${t.name}: ${t.description} (params: ${Object.keys(t.inputSchema.properties).join(", ")})`
    )
    .join("\n");

  const prompt = `You are Nova's mission planner. Given a user goal, create a detailed step-by-step plan.

Available tools:
${toolDescriptions}

User goal: "${goal}"

RULES:
1. Break the goal into concrete, executable steps.
2. Each step must use one of the available tools.
3. Steps that depend on previous results must list their dependencies.
4. Steps that are independent can run in parallel (set canRunInParallel: true).
5. Include verification steps where appropriate (e.g., after creating an event, verify it exists).
6. Be specific with arguments — use concrete values, not placeholders.
7. If the goal is ambiguous, include a clarification step that asks the user.
8. Maximum 10 steps.
9. For date/time references like "tomorrow", calculate the actual date.
10. For person references like "Rahul", use the name directly in search/query args.

Return ONLY a JSON object:
{
  "steps": [
    {
      "description": "human-readable step description",
      "tool": "tool.name",
      "args": { "key": "value" },
      "dependsOn": ["step_id_of_dependency"] or [],
      "canRunInParallel": false
    }
  ],
  "estimatedToolCalls": number,
  "reasoning": "brief explanation of the plan"
}

The "dependsOn" array should contain the index-based step ids: "step_0", "step_1", etc.
Return ONLY the JSON, no explanation outside it.`;

  try {
    const response = await callGemini(geminiKey, prompt, undefined, "reasoning");

    // Extract JSON from response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return fallbackPlan(goal);
    }

    const parsed = JSON.parse(jsonMatch[0]);

    if (!parsed.steps || !Array.isArray(parsed.steps) || parsed.steps.length === 0) {
      return fallbackPlan(goal);
    }

    // Map steps to MissionStep format
    const steps: MissionPlan["steps"] = parsed.steps.map(
      (s: any, i: number) => ({
        description: s.description || `Step ${i + 1}`,
        tool: s.tool || "",
        args: s.args || {},
        dependsOn: Array.isArray(s.dependsOn) ? s.dependsOn : [],
        canRunInParallel: Boolean(s.canRunInParallel),
      })
    );

    return {
      steps,
      estimatedToolCalls: parsed.estimatedToolCalls || steps.length,
      reasoning: parsed.reasoning || "Plan generated by AI",
    };
  } catch (err) {
    console.error("[MissionPlanner] Plan generation failed:", err);
    return fallbackPlan(goal);
  }
}

/**
 * Fallback plan when AI planning fails.
 * Creates a simple single-step plan that sends the goal to the chat AI.
 */
function fallbackPlan(goal: string): MissionPlan {
  return {
    steps: [
      {
        description: `Process request: "${goal.slice(0, 80)}"`,
        tool: "",
        args: { text: goal },
        dependsOn: [],
        canRunInParallel: false,
      },
    ],
    estimatedToolCalls: 1,
    reasoning: "AI planning unavailable — falling back to single-step processing",
  };
}

/**
 * Generate a re-plan after a step fails or produces unexpected results.
 */
export async function regeneratePlan(
  goal: string,
  completedSteps: MissionStep[],
  failedStep: MissionStep,
  geminiKey: string
): Promise<MissionPlan> {
  const completedSummary = completedSteps
    .map(
      (s) =>
        `- ${s.description}: ${s.result?.success ? "SUCCESS" : "FAILED"} — ${s.result?.message || s.result?.error || "no details"}`
    )
    .join("\n");

  const tools = toolRegistry.listAvailable();
  const toolDescriptions = tools
    .map(
      (t) =>
        `- ${t.name}: ${t.description} (params: ${Object.keys(t.inputSchema.properties).join(", ")})`
    )
    .join("\n");

  const prompt = `You are Nova's mission re-planner. A mission is in progress and a step failed.

Original goal: "${goal}"

Completed steps:
${completedSummary || "(none)"}

Failed step: "${failedStep.description}"
Tool: ${failedStep.tool}
Error: ${failedStep.error || "unknown"}

Available tools:
${toolDescriptions}

Create a new plan to achieve the original goal, considering what has already been done.
Use alternative tools or approaches if the original tool is failing.
Do NOT re-execute steps that already succeeded.

Return ONLY a JSON object with "steps", "estimatedToolCalls", and "reasoning" fields.
Steps use: description, tool, args, dependsOn (array of step ids like "step_0"), canRunInParallel.`;

  try {
    const response = await callGemini(geminiKey, prompt, undefined, "reasoning");
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return fallbackPlan(goal);

    const parsed = JSON.parse(jsonMatch[0]);
    if (!parsed.steps || !Array.isArray(parsed.steps) || parsed.steps.length === 0) {
      return fallbackPlan(goal);
    }

    return {
      steps: parsed.steps.map((s: any) => ({
        description: s.description || "Replanned step",
        tool: s.tool || "",
        args: s.args || {},
        dependsOn: Array.isArray(s.dependsOn) ? s.dependsOn : [],
        canRunInParallel: Boolean(s.canRunInParallel),
      })),
      estimatedToolCalls: parsed.estimatedToolCalls || parsed.steps.length,
      reasoning: parsed.reasoning || "Re-planned after failure",
    };
  } catch {
    return fallbackPlan(goal);
  }
}
